{
  "name": "ngx-builder",
  "descriptioin": "ngx-builder",
  "version": "0.0.3",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json",
    "analyze": "npm run clean && npm run build:prod  --aot --stats-json && webpack-bundle-analyzer ./dist/stats.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.4",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "^8.2.4",
    "@angular/compiler": "^8.2.4",
    "@angular/core": "^8.2.4",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "^8.2.4",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "^8.2.4",
    "@angular/platform-browser-dynamic": "^8.2.4",
    "@angular/router": "^8.2.4",
    "@ngx-formly/core": "^5.4.1",
    "@ngx-formly/material": "^5.4.1",
    "@ngx-progressbar/core": "^5.2.1",
    "@ngx-progressbar/http": "^5.2.1",
    "angular2-query-builder": "^0.4.2",
    "bcrypt": "^3.0.6",
    "core-js": "^3.2.1",
    "hammerjs": "^2.0.8",
    "html2canvas": "^1.0.0-rc.3",
    "jspdf": "^1.4.1",
    "ng-pick-datetime": "^7.0.0",
    "ng2-odometer": "^1.1.3",
    "ngx-image-cropper": "^1.4.1",
    "ngx-img-cropper": "^8.0.1",
    "rxjs": "^6.5.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.2",
    "@angular/cli": "^8.3.2",
    "@angular/compiler-cli": "^8.2.4",
    "@angular/language-service": "^8.2.4",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~12.7.3",
    "codelyzer": "^5.0.1",
    "compodoc": "0.0.41",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.1",
    "ts-node": "~8.3.0",
    "tslint": "~5.19.0",
    "typescript": "^3.5.3",
    "webpack-bundle-analyzer": "^3.4.1"
  }
 }
