CREATE TABLE `elemento` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `artefatofk` varchar(255) DEFAULT NULL,
  `decimais` bigint(20) DEFAULT NULL,
  `dica` varchar(255) DEFAULT NULL,
  `inicial` varchar(255) DEFAULT NULL,
  `label_prop` varchar(255) DEFAULT NULL,
  `mascara` varchar(255) DEFAULT NULL,
  `nome` varchar(255) DEFAULT NULL,
  `column_name` varchar(255) DEFAULT NULL,
  `options` varchar(255) DEFAULT NULL,
  `ordenation` bigint(20) DEFAULT NULL,
  `persistence` bit(1) NOT NULL,
  `pipe` varchar(255) DEFAULT NULL,
  `requerido` bit(1) NOT NULL,
  `minimo` bigint(20) DEFAULT NULL,
  `maximo` bigint(20) DEFAULT NULL,
  `linhas` bigint(20) DEFAULT NULL,
  `resource_prop` varchar(255) DEFAULT NULL,
  `rotulo` varchar(255) DEFAULT NULL,
  `showcolumn` bit(1) NOT NULL,
  `tamanho` bigint(5) DEFAULT NULL,
  `tipo_elemento` varchar(255) DEFAULT NULL,
  `tipo_field` varchar(255) DEFAULT NULL,
  `url_prop` varchar(255) DEFAULT NULL,
  `value_prop` varchar(255) DEFAULT NULL,
  `artefato_id` bigint(20) DEFAULT NULL,
  `field_group` bigint(20) DEFAULT NULL,
  `field_size` bigint(5) DEFAULT NULL, 
  `unique_key` bit(1) NULL,
  `unique_group` bigint(2) NULL,
  PRIMARY KEY (`id`) ,
  CONSTRAINT UK_NOME_IN_ELEMENTO UNIQUE (`artefato_id`,`nome`)
) ENGINE=InnoDB  DEFAULT CHARSET=UTF8MB4;
